export const MBTIQuestion = [
  //==================== E / I ====================
  {
    title: "我傾向從何處得到力量",
    option1: "別人。",
    option2: "我自己的想法。",
    result1: "E",
    result2: "I",
  },
  {
    title: "當我參加一個社交聚會時，我傾向有更多的力氣",
    option1: "在夜色很深時，一旦我開始投入，也許就是最晚離開的那一個。",
    option2: "在夜晚開始的時候，我就疲倦了並且想回家。",
    result1: "E",
    result2: "I",
  },
  {
    title: "下列哪一種聽起來比較吸引人？",
    option1: "到有很多人且社交活動頻繁的地方。",
    option2:
      "待在家中做一些特別的事情，例如說觀賞一部有趣的錄影帶並享用我最愛的外帶食物。",
    result1: "E",
    result2: "I",
  },
  {
    title: "在社交場合中，我通常：",
    option1: "整體來說蠻健談的。 ",
    option2: "較安靜並保留，直到我覺得舒服。",
    result1: "E",
    result2: "I",
  },
  {
    title: "我傾向擁有：",
    option1: "很多認識的人和很親密的朋友。 ",
    option2: "一些很親密的朋友和一些認識的人。",
    result1: "E",
    result2: "I",
  },
  //==================== N / S ====================
  {
    title: "我傾向透過以下方式收集資訊：",
    option1: "我對有可能發生之事的想像和期望。 ",
    option2: "我對目前狀況實際認知。",
    result1: "N",
    result2: "S",
  },
  {
    title: "我傾向相信：",
    option1: "我的直覺。 ",
    option2: "我直接的觀察和現成的經驗。",
    result1: "N",
    result2: "S",
  },
  {
    title: "當我對一個社交場合覺得放心時，我傾向談論：",
    option1:
      "未來，關於改進或發明事物，和生活的種種可能性。例如說，我也許會談論一個新的科學發明，或一個更好的方法來表達我的感受。",
    option2:
      "實際的，具體的，關於「此時此地」的事物。例如說，我也許會談論品酒的好方法，或我即將耍參加的新奇旅程。 ",
    result1: "N",
    result2: "S",
  },
  {
    title: "我是這種人：",
    option1: "喜歡先看整個大局面。",
    option2: "喜歡先拿握細節。 ",
    result1: "N",
    result2: "S",
  },
  {
    title: "我是這種型的人：",
    option1: "與其活在現實中，我選擇活在我的想像裡。",
    option2: "與其活在我的想像裡，我選擇活在現實中。 ",
    result1: "N",
    result2: "S",
  },

  //==================== F / T ====================

  {
    title: "我傾向如此做決定：",
    option1: "首先依我的心意，然依我的邏輯。",
    option2: "首先依我的邏輯，然後依我的心意。 ",
    result1: "F",
    result2: "T",
  },
  {
    title: "我傾向比較能夠察覺到：",
    option1: "當人們需要情感上的支持時。 ",
    option2: "當人們不合邏輯時。 ",
    result1: "F",
    result2: "T",
  },
  {
    title: "當我不同意別人的想法時：  ",
    option1:
      "我盡可能地避免傷害對方的感受；若是會對對方造成傷害的話，我就不會說。  ",
    option2: "我通常毫無保留地說話，並且向對方直言直語，因為對的就是對的。 ",
    result1: "F",
    result2: "T",
  },
  {
    title: "認識我的人傾向形容我為： ",
    option1: "熱情和敏感。",
    option2: "邏輯和明確。",
    result1: "F",
    result2: "T",
  },
  {
    title: "我把大部分和別人的相遇視為： ",
    option1: "友善及重要的。",
    option2: "另有目的。",
    result1: "F",
    result2: "T",
  },

  //==================== J / P ====================
  {
    title: "若我有時間和金錢，朋友邀請我到國外度假，並且在一天前才通知，我會：",
    option1: "必須先檢查我的時間表。 ",
    option2: "立即收拾行裝。",
    result1: "J",
    result2: "P",
  },
  {
    title: "我選擇的生活循環著：",
    option1: "日程表和組織。  ",
    option2: "自然發生和彈性。",
    result1: "J",
    result2: "P",
  },
  {
    title: "哪一項較為常見：",
    option1: "我準時出席而其他人遲到。   ",
    option2: "其他人都準則出席而我遲到。",
    result1: "J",
    result2: "P",
  },
  {
    title: "我是這樣喜歡……的人：",
    option1: "下定決心並且做出最後肯定的結論。   ",
    option2: "開放我的選擇並且持續收集資訊。",
    result1: "J",
    result2: "P",
  },
  {
    title: "我是這類型的人：",
    option1: "喜歡在一個時間裡專心於一件事情直到完成。",
    option2: "享受同時進行好幾件事情。",
    result1: "J",
    result2: "P",
  },
];

export const DISCQuestion = [
  {
    title: "當你和朋友一起用餐時，在選擇用餐或是吃什麼時，你常是 :",
    option1: "決定者：意見不同時，通常都是決定者。",
    option2: "氣氛製造者：吃什麼，很能帶動情緒氣氛。",
    option3: "附和者：隨便，沒意見。",
    option4: "意見提供者：常去否定別人的提議，自己卻又沒意見，也不做任何決定。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "當你買衣服時，你是 :",
    option1: "不易受售貨員影響，“ 心中自有定見。",
    option2: "售貨員的親切及好的感受，常會促進你的購買。",
    option3: "找熟悉的店購買。",
    option4: "品質與價錢是否成比例，價錢是否合理?",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "你的消費習慣是 :",
    option1: "找到要買的東西，付錢走人。",
    option2: "很隨意的逛，不特定買什麼。",
    option3: "有一定的消費習慣，不太喜歡變化。",
    option4: "較注意東西好不好，較有成本觀念。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "你的朋友，以一句話來形容你，他們會說 :",
    option1: "蠻”鴨霸”的。",
    option2: "熱情洋溢。",
    option3: "溫和斯文。",
    option4: "要求完美。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "你自認那一種形容，最能表現你的特色：",
    option1: "果敢的，能接受挑戰。",
    option2: "生動活潑，不拘小節。",
    option3: "愛傾聽，喜歡穩定。",
    option4: "處世謹慎小心，重數據分析。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "你覺得做事的重點，應該是 : ",
    option1: "what，做什麼? 重結果。",
    option2: "who，誰來做? 重感受(過程)",
    option3: "why，為何做? 重品質。",
    option4: "怎麼做? 重執行。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "與同事有意見衝突(或不同)時，你是 : ",
    option1: "說服對方，聽從自己的意見。",
    option2: "問其他同事或上司之意見，尋求支持。",
    option3: "退讓，以和為貴。",
    option4: "與衝突者協調，找尋最好的意見。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "什麼樣的工作環境，最能鼓舞你 : ",
    option1: "能讓你決定事情，具領導地位的。",
    option2: "同事相處愉快，處處受歡迎。",
    option3: "穩定中求發展。",
    option4: "講品質，重效率的工作。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "以下的溝通方式，那一項最符合你 : ",
    option1: "直接了當，較權威式的。",
    option2: "表情豐富，肢體語言較多。",
    option3: "先聽聽別人意見，而後溫和的表達自己的意見。",
    option4: "不露感情的，理多於情，愛分析，較冷靜。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
  {
    title: "在每一次會議中或公司決議提案時，你所扮演的角色為何 : ",
    option1: "據理力爭者。",
    option2: "協調者。",
    option3: "協調者。",
    option4: "分析所有提案以供參考者。",
    result1: "Tiger",
    result2: "Peacock",
    result3: "KoalaBear",
    result4: "Owl",
  },
];
